language: ruby
sudo: false
script: rake test
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head
# before_install:
  # - gem install rake minitest
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
